services:
  - type: web
    name: recruitmente2e
    env: docker
    plan: free
    region: oregon
    repo: https://github.com/RishavKumar8578/recruitmente2e
    branch: main
    dockerfilePath: ./Dockerfile
    envVars:
      # Matches application.properties exactly
      - key: DB_HOST
        value: dpg-d1v03049c44c73ddaus0-a        # Replace with your Render DB host
      - key: DB_PORT
        value: 5432
      - key: DB_NAME
        value: recruitmente2e              # Replace with your DB name
      - key: DB_USER
        value: recruitmente2e_user                  # Replace with your DB username
      - key: DB_PASSWORD
        value: NQtI7YDarPmEMkiHZ4SfCYaDkCTRA9Mn              # Replace with your DB password

      # Optional: profile
      - key: SPRING_PROFILES_ACTIVE
        value: prod

      # Mail config (already used in properties)
      - key: SPRING_MAIL_USERNAME
        value: corebursanarishav@gmail.com
      - key: SPRING_MAIL_PASSWORD
        value: vdvm jyek oern sbyy

      # Ollama config (optional — may not work in cloud)
      - key: SPRING_AI_OLLAMA_BASE_URL
        value: http://localhost:11434
